author: Search.gov
title: Search.gov
url: https://search.gov
permalink: /:categories/:title.html
lsi: false
highlighter: pygments
markdown: kramdown
exclude: [.gitignore, .rvmrc, Gemfile, Gemfile.lock, README.md, Rakefile, config.rb, sass, vendor]

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  parse_block_html: true

# plugin config
paginate_per_page: 10
posts_paginate_path: blog/page:num
posts_paginate_layout: paginate
posts_tag_layout: tag

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
