auto: true
author: DIGITALGOV | Search
title: DIGITALGOV | Search
url: http://search.digitalgov.gov
permalink: /blog/:title.html
lsi: false
pygments: true
markdown: rdiscount
exclude: [.gitignore, .rvmrc, Gemfile, Gemfile.lock, README.md, Rakefile, config.rb, sass, vendor]
server: true

# plugin config
paginate_per_page: 10
posts_paginate_path: blog/page:num
posts_paginate_layout: paginate
posts_tag_layout: tag
